/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './web/**/*.html',
    './web/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        "primary":                   "#b7131a",
        "primary-container":         "#db322f",
        "on-primary":                "#ffffff",
        "on-primary-container":      "#fffbff",
        "background":                "#f8f9fc",
        "surface":                   "#f8f9fc",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#f2f3f6",
        "surface-container":         "#edeef1",
        "surface-container-high":    "#e7e8eb",
        "surface-container-highest": "#e1e2e5",
        "on-surface":                "#191c1e",
        "on-surface-variant":        "#5b403d",
        "secondary":                 "#4c56af",
        "on-secondary":              "#ffffff",
        "secondary-container":       "#959efd",
        "secondary-fixed":           "#e0e0ff",
        "on-secondary-fixed":        "#000767",
        "tertiary":                  "#006578",
        "outline":                   "#906f6c",
        "outline-variant":           "#e4beb9",
        "inverse-surface":           "#2e3133",
        "inverse-on-surface":        "#f0f1f4",
        "primary-fixed":             "#ffdad6",
        "primary-fixed-dim":         "#ffb4ac",
        "inverse-primary":           "#ffb4ac",
        "error":                     "#ba1a1a",
        "error-container":           "#ffdad6",
        "on-error":                  "#ffffff",
        "on-error-container":        "#93000a",
        "surface-dim":               "#d9dadd",
        "surface-bright":            "#f8f9fc",
        "surface-tint":              "#bb171c",
        "surface-variant":           "#e1e2e5",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body":     ["Plus Jakarta Sans"],
        "label":    ["Plus Jakarta Sans"],
      },
    },
  },
  plugins: [],
}
